apiVersion: v1
kind: Namespace
metadata:
  name: configmap-watcher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: configmap-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-watcher
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-watcher-binding
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: configmap-watcher
roleRef:
  kind: ClusterRole
  name: configmap-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-watcher
  namespace: configmap-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-watcher
  template:
    metadata:
      labels:
        app: configmap-watcher
    spec:
      serviceAccountName: watcher
      containers:
        - name: watcher
          image: prasadb89/configmap-watcher
          command: ["/configmap-watcher"]
